// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwcExcKgxnmO5OS5LF0oTLSRwJh_SiWWU',
    appId: '1:995621563150:web:5612e38437b9e8a015c55f',
    messagingSenderId: '995621563150',
    projectId: 'ecommerc-56077',
    authDomain: 'ecommerc-56077.firebaseapp.com',
    storageBucket: 'ecommerc-56077.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYFfUjIsJVjn06nhVl5UvNv0e-1Q5sSN8',
    appId: '1:995621563150:android:b4c7f64ee711755315c55f',
    messagingSenderId: '995621563150',
    projectId: 'ecommerc-56077',
    storageBucket: 'ecommerc-56077.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAab4zYUxvRv5UnoVoLvFbNGliOUd1MN9I',
    appId: '1:995621563150:ios:983cae1b7c52ecfb15c55f',
    messagingSenderId: '995621563150',
    projectId: 'ecommerc-56077',
    storageBucket: 'ecommerc-56077.appspot.com',
    iosBundleId: 'com.example.firebaseecom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAab4zYUxvRv5UnoVoLvFbNGliOUd1MN9I',
    appId: '1:995621563150:ios:983cae1b7c52ecfb15c55f',
    messagingSenderId: '995621563150',
    projectId: 'ecommerc-56077',
    storageBucket: 'ecommerc-56077.appspot.com',
    iosBundleId: 'com.example.firebaseecom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwcExcKgxnmO5OS5LF0oTLSRwJh_SiWWU',
    appId: '1:995621563150:web:09587218fc1823bf15c55f',
    messagingSenderId: '995621563150',
    projectId: 'ecommerc-56077',
    authDomain: 'ecommerc-56077.firebaseapp.com',
    storageBucket: 'ecommerc-56077.appspot.com',
  );
}
